### ISSUE TITLE
readme 

### ISSUE THREAD

**Issue by frknbasaran** [erayarslan/qop-node-testdb#1]
readme yaz da neyi starladığımızı bilelim boş senede imza atıyoz senin yüzünden

**Comment by erayarslan** [comment]
kanka bu çöp kod.
tcp/ip bağlantısı için sanal bi db olsun diye yazmıştım.
pc'de duracağına burda dursun : D

tşkkrlr sprmn. :star:laman yeter pardon düşünmen.
